#!/bin/bash
###
# This is the main configuration file of the ESO-Database Steam Deck Client.
#
# Please do not edit this file, because it will be overwritten during the update!
# If you want to make your own configurations,
# rename the file user.config.example.sh to user.config.sh and overwrite the variables there.
###


##
# Proton
##

# The Elder Scrolls Online Steam App ID (See: https://steamdb.info/app/306130/)
export ESODB_ESO_STEAM_APP_ID=306130
# The Proton path of the Elder Scrolls Online live data folder
export ESODB_ESO_PROTON_PATH="/home/deck/.local/share/Steam/steamapps/compatdata/${ESODB_ESO_STEAM_APP_ID}/pfx/drive_c/users/steamuser/Documents/Elder Scrolls Online/live"
# The Elder Scrolls Online Proton live AddOns path
export ESODB_ESO_PROTON_ADDONS_LIVE_PATH="${ESODB_ESO_PROTON_PATH}/AddOns"
# The Elder Scrolls Online Proton live SavedVariables path
export ESODB_ESO_PROTON_SV_PATH="${ESODB_ESO_PROTON_PATH}/SavedVariables"
# The SavedVariables file name of the main export
export ESODB_SV_EXPORT_FILE_NAME="ESODatabaseExport.lua"
# The Elder Scrolls Online Proton live SavedVariables file path for the main export file
export ESODB_ESO_PROTON_EXPORT_ADDON_SV_FILE="${ESODB_ESO_PROTON_SV_PATH}/${ESODB_SV_EXPORT_FILE_NAME}"
# The SavedVariables file name of the game data export
export ESODB_SV_GAME_DATA_FILE_NAME="ESODatabaseGameDataExport.lua"
# The Elder Scrolls Online Proton live SavedVariables file path for the game data export file
export ESODB_ESO_PROTON_GAME_DATA_ADDON_SV_FILE="${ESODB_ESO_PROTON_SV_PATH}/${ESODB_SV_GAME_DATA_FILE_NAME}"
# The SavedVariables file name of the leaderboard export
export ESODB_SV_LEADERBOARD_FILE_NAME="ESODatabaseLeaderboardExport.lua"
# The Elder Scrolls Online Proton live SavedVariables file path for the leaderboard export file
export ESODB_ESO_PROTON_LEADERBOARD_ADDON_SV_FILE="${ESODB_ESO_PROTON_SV_PATH}/${ESODB_SV_LEADERBOARD_FILE_NAME}"

##
# Desktop
##

# The timeout in milliseconds at which to expire the notifications
export ESODB_DESKTOP_NOTIFICATIONS_EXPIRE=10000

##
# Uploader
##

# The number of seconds to wait before a new file check interaction is started
export ESODB_UPLOADER_SLEEP_TIME=15
# Enables (1) or disables (0) the data compression before upload
export ESODB_UPLOADER_COMPRESSION=1
# Enables the data compression before upload. (Valid range 1-9, default 5)
export ESODB_UPLOADER_COMPRESSION_LEVEL=5
# The temporary path for the uploader
export ESODB_UPLOADER_TMP_PATH="/tmp/.esodb_upload"
# The upload URL of the ESO-Database server for the Steam Deck
export ESODB_UPLOAD_EXPORT_URL="https://data.eso-database.com/v3/upload/data-exporter/"
# Enables (1) or disables (0) the game data export upload
export ESODB_UPLOADER_ENABLE_GAME_DATA=1
# The game data upload URL of the ESO-Database server for the Steam Deck
export ESODB_UPLOADER_GAME_DATA_URL="https://data.eso-database.com/v3/upload/game-data-exporter/"
# Enables (1) or disables (0) the leaderboard data export upload
export ESODB_UPLOADER_ENABLE_LEADERBOARD_DATA=1
# The leaderboard data upload URL of the ESO-Database server for the Steam Deck
export ESODB_UPLOADER_LEADERBOARD_DATA_URL="https://data.eso-database.com/v3/upload/leaderboard-data-exporter/"

##
# Paths
##

# The ESO-Database Steam Deck Client data path
export ESODB_APP_DATA_PATH="/home/deck/.eso-database-client"
# The ESO-Database Steam Deck Client meta data path
export ESODB_META_ADDON_DIR="${ESODB_APP_DATA_PATH}/meta"
# The ESO-Database Steam Deck Client AddOn meta data file
export ESODB_META_ADDON_FILE="${ESODB_META_ADDON_DIR}/addons.json"
# The temporary download location path
export ESODB_DOWNLOAD_TEMP_DIR="/tmp/.esodb_download"
# The path to the authentication file that stores the information for the currently logged in user
export ESODB_AUTH_FILE="${ESODB_APP_DATA_PATH}/auth"

##
# API
##

# The user agent that is used for all server connections
export ESODB_API_USER_AGENT="ESODBClient/Steam-Deck"
# The authentication indicator of the ESO-Database Steam Deck client
export ESODB_AUTH_SOURCE="steam-deck"

##
# API endpoints
##

# The endpoint to fetch AddOn information
export ESODB_API_GET_ADDON_VERSIONS="https://api.eso-database.com/v2/api/get-addon-versions"
# The endpoint to fetch authorization request token for the login process
export ESODB_AUTH_API_URL="https://auth.eso-database.com/api/new_request.php"
# The endpoint to fetch the authentication status of the user
export ESODB_AUTH_API_GET_AUTH_STATUS="https://auth.eso-database.com/api/get_auth_status.php"
# The endpoint for redirecting the user to the authorization page in their preferred browser language
export ESODB_AUTH_USER_URL="https://auth.eso-database.com/redirect-auth"


# Source user config file if available
if [ -f "/home/deck/Applications/ESO-Database/config/user.config.sh" ]; then
	source /home/deck/Applications/ESO-Database/config/user.config.sh
fi
