name: Build release package

on:
  push:
    tags:
      - '**'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create release ZIP package
        run: zip -r eso-database-steam-deck.zip assets/ config/ install/ scripts/ version.txt

      - name: Get release changelog
        run: $(php -r "preg_match_all('/((?:# ${{ github.ref_name }}\R)((-(.*)\R+)+))/m', file_get_contents('./CHANGELOG.md'), \$matches); echo trim(\$matches[2][0]);" > changelog.txt)

      - name: Read changelog from file
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.txt
          trim: true

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./eso-database-steam-deck.zip
          tag: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          overwrite: true
          body: "${{ steps.changelog.outputs.content }}"
