name: Build release package

on:
  push:
    branches:
      - develop

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get release changelog
        run: |
          full_changelog=$(cat CHANGELOG.md)
          changelog=$(php -r "preg_match_all('/((?:# ${{ github.ref_name }}\R)((-(.*)\R+)+))/m', '${full_changelog}', \$matches); echo trim(\$matches[2][0]);")
          echo "${changelog}" > changelog.txt

      - name: Read changelog from file
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.txt
          trim: true

      - name: Test
        run: |
          echo "${{ steps.changelog.outputs.content }}"
